default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: 5

development:
  <<: *default
  database: local-achieve_development

test:
  <<: *default
  database: local-achieve_test


production:
  <<: *default
  database: local-achieve_production
  username: local-achieve
  password: <%= ENV['LOCAL-ACHIEVE_DATABASE_PASSWORD'] %>
